'use strict';

// [v3.0, E6-T1] Formatting linter for the Document Formatting Standard
// (manual.md / framework.md § Document Formatting Standard, Rules 1-2:
// separator dashes match column width, data cells padded to fill it).
//
// Deliberately reuses renderTable() from markdown-table.js — the exact same
// function every write tool already goes through — as the sole definition
// of "compliant." This is not a second, parallel implementation of the
// standard that could drift from the one the write tools already enforce
// (Principle 26): a table is compliant if and only if re-rendering it with
// renderTable() reproduces its current lines verbatim.
//
// Scope: only Rules 1-2 (mechanically checkable per table, with no
// semantic judgment required). Rule 3 (consistent widths for the same
// schema across files) and Rule 4 (blank separator rows between logical
// groups) are not checked — both require recognizing "the same schema" or
// "a logical group," which is a semantic judgment call, not a mechanical
// one. Documented here rather than silently omitted.
//
// Also does not check (and will report as violations, correctly, since
// AOSDF's own standard never defines them) GFM alignment-colon separators
// (`:---`, `:--:`, `---:`) — the Document Formatting Standard has no
// alignment-marker concept, and a repo-wide scan (E6-T1) found zero
// existing tables using them.

const fs = require('fs');
const path = require('path');
const { findTables, renderTable } = require('./markdown-table');

const DEFAULT_IGNORE_DIRS = new Set(['node_modules', '.git', '.venv', '.vscode']);
// Built site output is generated by mkdocs from the source markdown, not
// hand-authored or agent-written — linting it would just re-report every
// violation (if any) already caught in the source, against files no agent
// ever edits directly.
const SITE_DIR_SUFFIX = '-site';

function findMarkdownFiles(root) {
  const results = [];
  function walk(dir) {
    let entries;
    try {
      entries = fs.readdirSync(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const entry of entries) {
      if (entry.name.startsWith('.') && entry.name !== '.') continue;
      const full = path.join(dir, entry.name);
      if (entry.isDirectory()) {
        if (DEFAULT_IGNORE_DIRS.has(entry.name)) continue;
        if (entry.name.endsWith(SITE_DIR_SUFFIX)) continue;
        walk(full);
      } else if (entry.isFile() && entry.name.endsWith('.md')) {
        results.push(full);
      }
    }
  }
  walk(root);
  return results;
}

// Returns violations for one file's content: [{ line, table, expected, actual }]
// `line` is the 1-indexed source line of the first non-compliant row in the table.
function lintContent(content) {
  const lines = content.split('\n');
  const tables = findTables(lines);
  const violations = [];

  for (const table of tables) {
    const original = lines.slice(table.headerLineIdx, table.endLineIdx);
    const canonical = renderTable(table.header, table.rows);
    if (original.length !== canonical.length) {
      // Only possible if a data row itself contains a literal newline,
      // which splitRow/findTables cannot produce from well-formed input.
      violations.push({
        line: table.headerLineIdx + 1,
        table,
        expected: canonical,
        actual: original,
      });
      continue;
    }
    for (let i = 0; i < original.length; i++) {
      if (original[i] !== canonical[i]) {
        violations.push({
          line: table.headerLineIdx + 1,
          table,
          expected: canonical,
          actual: original,
        });
        break;
      }
    }
  }

  return violations;
}

// Rewrites `content` so every table is canonical. Returns the new content
// (identical to the input if there was nothing to fix).
function fixContent(content) {
  const lines = content.split('\n');
  const tables = findTables(lines);
  // Apply bottom-most table first so earlier line indices don't shift.
  const sorted = [...tables].sort((a, b) => b.headerLineIdx - a.headerLineIdx);
  let result = lines;
  for (const table of sorted) {
    const canonical = renderTable(table.header, table.rows);
    result = [...result.slice(0, table.headerLineIdx), ...canonical, ...result.slice(table.endLineIdx)];
  }
  return result.join('\n');
}

// Lints every .md file under `root`. Returns [{ file, violations }] — only
// for files with at least one violation.
function lintTree(root) {
  const files = findMarkdownFiles(root);
  const report = [];
  for (const file of files) {
    const content = fs.readFileSync(file, 'utf8');
    const violations = lintContent(content);
    if (violations.length > 0) report.push({ file, violations });
  }
  return report;
}

// Fixes every .md file under `root` in place. Returns the list of file
// paths actually changed.
function fixTree(root) {
  const files = findMarkdownFiles(root);
  const changed = [];
  for (const file of files) {
    const content = fs.readFileSync(file, 'utf8');
    const fixed = fixContent(content);
    if (fixed !== content) {
      fs.writeFileSync(file, fixed);
      changed.push(file);
    }
  }
  return changed;
}

module.exports = {
  findMarkdownFiles,
  lintContent,
  fixContent,
  lintTree,
  fixTree,
};
